<?php
function show_product_attribute($attribute_type, $attribute_value)
{
	$img_attribute = "";
	if($attribute_type == "Local Produce" && $attribute_value == "Yes")
		$img_attribute .= "<img src='".ECART_URL."images/notes/local.gif'>";
   
	if($attribute_type == "Gluten Free" && $attribute_value == "Yes")
		$img_attribute .= "<img src='".ECART_URL."images/notes/glutenfree.gif'>";

	return "<div align='center' class='att'>".$img_attribute."</div>";
}

function timezone_convert($offset){
	$zone = array(
			'(-11) Midway Island' => 'Pacific/Midway',
			'(-11) Samoa' => 'Pacific/Samoa',
			'(-10) Hawaii' => 'Pacific/Honolulu',
			'(-9) Alaska' => 'US/Alaska',
			'(-8) Pacific Time (US &amp; Canada)' => 'America/Los_Angeles',
			'(-8) Tijuana' => 'America/Tijuana',
			'(-7) Arizona' => 'US/Arizona',
			'(-7) Chihuahua' => 'America/Chihuahua',
			'(-7) La Paz' => 'America/Chihuahua',
			'(-7) Mazatlan' => 'America/Mazatlan',
			'(-7) Mountain Time (US &amp; Canada)' => 'US/Mountain',
			'(-6) Central America' => 'America/Managua',
			'(-6) Central Time (US &amp; Canada)' => 'US/Central',
			'(-6) Guadalajara' => 'America/Mexico_City',
			'(-6) Mexico City' => 'America/Mexico_City',
			'(-6) Monterrey' => 'America/Monterrey',
			'(-6) Saskatchewan' => 'Canada/Saskatchewan',
			'(-5) Bogota' => 'America/Bogota',
			'(-5) Eastern Time (US &amp; Canada)' => 'US/Eastern',
			'(-5) Indiana (East)' => 'US/East-Indiana',
			'(-5) Lima' => 'America/Lima',
			'(-5) Quito' => 'America/Bogota',
			'(-4) Atlantic Time (Canada)' => 'Canada/Atlantic',
			'(-4.5) Caracas' => 'America/Caracas',
			'(-4) La Paz' => 'America/La_Paz',
			'(-4) Santiago' => 'America/Santiago',
			'(-3.5) Newfoundland' => 'Canada/Newfoundland',
			'(-3) Brasilia' => 'America/Sao_Paulo',
			'(-3) Buenos Aires' => 'America/Argentina/Buenos_Aires',
			'(-3) Georgetown' => 'America/Argentina/Buenos_Aires',
			'(-3) Greenland' => 'America/Godthab',
			'(-2) Mid-Atlantic' => 'America/Noronha',
			'(-1) Azores' => 'Atlantic/Azores',
			'(-1) Cape Verde Is.' => 'Atlantic/Cape_Verde',
			'(0) Casablanca' => 'Africa/Casablanca',
			'(0) Edinburgh' => 'Europe/London',
			'(0) Greenwich Mean Time : Dublin' => 'Etc/Greenwich',
			'(0) Lisbon' => 'Europe/Lisbon',
			'(0) London' => 'Europe/London',
			'(0) Monrovia' => 'Africa/Monrovia',
			'(1) Amsterdam' => 'Europe/Amsterdam',
			'(1) Belgrade' => 'Europe/Belgrade',
			'(1) Berlin' => 'Europe/Berlin',
			'(1) Bern' => 'Europe/Berlin',
			'(1) Bratislava' => 'Europe/Bratislava',
			'(1) Brussels' => 'Europe/Brussels',
			'(1) Budapest' => 'Europe/Budapest',
			'(1) Copenhagen' => 'Europe/Copenhagen',
			'(1) Ljubljana' => 'Europe/Ljubljana',
			'(1) Madrid' => 'Europe/Madrid',
			'(1) Paris' => 'Europe/Paris',
			'(1) Prague' => 'Europe/Prague',
			'(1) Rome' => 'Europe/Rome',
			'(1) Sarajevo' => 'Europe/Sarajevo',
			'(1) Skopje' => 'Europe/Skopje',
			'(1) Stockholm' => 'Europe/Stockholm',
			'(1) Vienna' => 'Europe/Vienna',
			'(1) Warsaw' => 'Europe/Warsaw',
			'(1) West Central Africa' => 'Africa/Lagos',
			'(1) Zagreb' => 'Europe/Zagreb',
			'(2) Athens' => 'Europe/Athens',
			'(2) Bucharest' => 'Europe/Bucharest',
			'(2) Cairo' => 'Africa/Cairo',
			'(2) Harare' => 'Africa/Harare',
			'(2) Helsinki' => 'Europe/Helsinki',
			'(2) Istanbul' => 'Europe/Istanbul',
			'(2) Jerusalem' => 'Asia/Jerusalem',
			'(2) Kyiv' => 'Europe/Helsinki',
			'(2) Pretoria' => 'Africa/Johannesburg',
			'(2) Riga' => 'Europe/Riga',
			'(2) Sofia' => 'Europe/Sofia',
			'(2) Tallinn' => 'Europe/Tallinn',
			'(2) Vilnius' => 'Europe/Vilnius',
			'(3) Baghdad' => 'Asia/Baghdad',
			'(3) Kuwait' => 'Asia/Kuwait',
			'(3) Minsk' => 'Europe/Minsk',
			'(3) Nairobi' => 'Africa/Nairobi',
			'(3) Riyadh' => 'Asia/Riyadh',
			'(3) Volgograd' => 'Europe/Volgograd',
			'(3.5) Tehran' => 'Asia/Tehran',
			'(4) Abu Dhabi' => 'Asia/Muscat',
			'(4) Baku' => 'Asia/Baku',
			'(4) Moscow' => 'Europe/Moscow',
			'(4) Muscat' => 'Asia/Muscat',
			'(4) St. Petersburg' => 'Europe/Moscow',
			'(4) Tbilisi' => 'Asia/Tbilisi',
			'(4) Yerevan' => 'Asia/Yerevan',
			'(4.5) Kabul' => 'Asia/Kabul',
			'(5) Islamabad' => 'Asia/Karachi',
			'(5) Karachi' => 'Asia/Karachi',
			'(5) Tashkent' => 'Asia/Tashkent',
			'(5.5) Chennai' => 'Asia/Calcutta',
			'(5.5) Kolkata' => 'Asia/Kolkata',
			'(5.5) Mumbai' => 'Asia/Calcutta',
			'(5.5) New Delhi' => 'Asia/Calcutta',
			'(5.5) Sri Jayawardenepura' => 'Asia/Calcutta',
			'(5.75) Kathmandu' => 'Asia/Katmandu',
			'(6) Almaty' => 'Asia/Almaty',
			'(6) Astana' => 'Asia/Dhaka',
			'(6) Dhaka' => 'Asia/Dhaka',
			'(6) Ekaterinburg' => 'Asia/Yekaterinburg',
			'(6.5) Rangoon' => 'Asia/Rangoon',
			'(7) Bangkok' => 'Asia/Bangkok',
			'(7) Hanoi' => 'Asia/Bangkok',
			'(7) Jakarta' => 'Asia/Jakarta',
			'(7) Novosibirsk' => 'Asia/Novosibirsk',
			'(8) Beijing' => 'Asia/Hong_Kong',
			'(8) Chongqing' => 'Asia/Chongqing',
			'(8) Hong Kong' => 'Asia/Hong_Kong',
			'(8) Krasnoyarsk' => 'Asia/Krasnoyarsk',
			'(8) Kuala Lumpur' => 'Asia/Kuala_Lumpur',
			'(8) Perth' => 'Australia/Perth',
			'(8) Singapore' => 'Asia/Singapore',
			'(8) Taipei' => 'Asia/Taipei',
			'(8) Ulaan Bataar' => 'Asia/Ulan_Bator',
			'(8) Urumqi' => 'Asia/Urumqi',
			'(9) Irkutsk' => 'Asia/Irkutsk',
			'(9) Osaka' => 'Asia/Tokyo',
			'(9) Sapporo' => 'Asia/Tokyo',
			'(9) Seoul' => 'Asia/Seoul',
			'(9) Tokyo' => 'Asia/Tokyo',
			'(9.5) Adelaide' => 'Australia/Adelaide',
			'(9.5) Darwin' => 'Australia/Darwin',
			'(10) Brisbane' => 'Australia/Brisbane',
			'(10) Canberra' => 'Australia/Canberra',
			'(10) Guam' => 'Pacific/Guam',
			'(10) Hobart' => 'Australia/Hobart',
			'(10) Melbourne' => 'Australia/Melbourne',
			'(10) Port Moresby' => 'Pacific/Port_Moresby',
			'(10) Sydney' => 'Australia/Sydney',
			'(10) Yakutsk' => 'Asia/Yakutsk',
			'(11) Vladivostok' => 'Asia/Vladivostok',
			'(12) Auckland' => 'Pacific/Auckland',
			'(12) Fiji' => 'Pacific/Fiji',
			'(12) International Date Line West' => 'Pacific/Kwajalein',
			'(12) Kamchatka' => 'Asia/Kamchatka',
			'(12) Magadan' => 'Asia/Magadan',
			'(12) Marshall Is.' => 'Pacific/Fiji',
			'(12) New Caledonia' => 'Asia/Magadan',
			'(12) Solomon Is.' => 'Asia/Magadan',
			'(12) Wellington' => 'Pacific/Auckland',
			'(12.75) Chatham Islands Time' => 'Pacific/Chatham',
			'(13) Nuku\'alofa' => 'Pacific/Tongatapu',
			'(14) Kiritimati' => 'Pacific/Kiritimati'
	);
	$data = "";
	foreach($zone as $key=>$value){
		$temp = explode(" ",$key,2);
		$fixoffset = "(".$offset.")";
		if($temp[0]==$fixoffset){
			$data = $value;
			break;
		}
	}
	return $data;
}


?>